"""add question flow

Revision ID: b6501ab469b2
Revises: cc8aebc88b25
Create Date: 2026-02-23 03:55:43.993364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6501ab469b2'
down_revision = 'cc8aebc88b25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_flows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('question_flows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_flows_user_id'), ['user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_flows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_flows_user_id'))

    op.drop_table('question_flows')
    # ### end Alembic commands ###
