"""add mood entries

Revision ID: f2e359954058
Revises: 7b4c491d8257
Create Date: 2026-02-23 03:43:16.756564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2e359954058'
down_revision = '7b4c491d8257'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mood_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mood', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mood_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mood_entries_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_mood_entries_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mood_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mood_entries_user_id'))
        batch_op.drop_index(batch_op.f('ix_mood_entries_created_at'))

    op.drop_table('mood_entries')
    # ### end Alembic commands ###
